name: textlint

on: [push]

jobs:
  textlint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install deps
      run: yarn
    - name: Run textlint
      run: yarn lint
